
    -- a_c_bear_01
    ['perfect_bear_pelt']        = {['name'] = 'perfect_bear_pelt',        ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bear_pelt']           = {['name'] = 'good_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bear_pelt']           = {['name'] = 'poor_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bearblack_01
    ['perfect_black_bear_pelt']  = {['name'] = 'perfect_black_bear_pelt',  ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_black_bear_pelt']     = {['name'] = 'good_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_black_bear_pelt']     = {['name'] = 'poor_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_boar_01
    ['perfect_boar_pelt']        = {['name'] = 'perfect_boar_pelt',        ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_boar_pelt']           = {['name'] = 'good_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_boar_pelt']           = {['name'] = 'poor_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buck_01
    ['perfect_buck_pelt']        = {['name'] = 'perfect_buck_pelt',        ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buck_pelt']           = {['name'] = 'good_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buck_pelt']           = {['name'] = 'poor_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buffalo_01
    ['perfect_buffalo_pelt']     = {['name'] = 'perfect_buffalo_pelt',     ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buffalo_pelt']        = {['name'] = 'good_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buffalo_pelt']        = {['name'] = 'poor_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bull_01
    ['perfect_bull_pelt']        = {['name'] = 'perfect_bull_pelt',        ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bull_pelt']           = {['name'] = 'good_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bull_pelt']           = {['name'] = 'poor_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cougar_01
    ['perfect_cougar_pelt']      = {['name'] = 'perfect_cougar_pelt',      ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cougar_pelt']         = {['name'] = 'good_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cougar_pelt']         = {['name'] = 'poor_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cow
    ['perfect_cow_pelt']         = {['name'] = 'perfect_cow_pelt',         ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cow_pelt']            = {['name'] = 'good_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cow_pelt']            = {['name'] = 'poor_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_coyote_01
    ['perfect_coyote_pelt']      = {['name'] = 'perfect_coyote_pelt',      ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_coyote_pelt']         = {['name'] = 'good_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_coyote_pelt']         = {['name'] = 'poor_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_deer_01
    ['perfect_deer_pelt']        = {['name'] = 'perfect_deer_pelt',        ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_deer_pelt']           = {['name'] = 'good_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_deer_pelt']           = {['name'] = 'poor_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_elk_01
    ['perfect_elk_pelt']         = {['name'] = 'perfect_elk_pelt',         ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_elk_pelt']            = {['name'] = 'good_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_elk_pelt']            = {['name'] = 'poor_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_fox_01
    ['perfect_fox_pelt']         = {['name'] = 'perfect_fox_pelt',         ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_fox_pelt']            = {['name'] = 'good_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_fox_pelt']            = {['name'] = 'poor_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_goat_01
    ['perfect_goat_pelt']        = {['name'] = 'perfect_goat_pelt',        ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_goat_pelt']           = {['name'] = 'good_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_goat_pelt']           = {['name'] = 'poor_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_javelina_01
    ['perfect_javelina_pelt']    = {['name'] = 'perfect_javelina_pelt',    ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_javelina_pelt']       = {['name'] = 'good_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_javelina_pelt']       = {['name'] = 'poor_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_moose_01
    ['perfect_moose_pelt']       = {['name'] = 'perfect_moose_pelt',       ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_moose_pelt']          = {['name'] = 'good_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_moose_pelt']          = {['name'] = 'poor_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_ox_01
    ['perfect_ox_pelt']          = {['name'] = 'perfect_ox_pelt',          ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_ox_pelt']             = {['name'] = 'good_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_ox_pelt']             = {['name'] = 'poor_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_panther_01
    ['perfect_panther_pelt']     = {['name'] = 'perfect_panther_pelt',     ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_panther_pelt']        = {['name'] = 'good_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_panther_pelt']        = {['name'] = 'poor_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pig_01
    ['perfect_pig_pelt']         = {['name'] = 'perfect_pig_pelt',         ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pig_pelt']            = {['name'] = 'good_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pig_pelt']            = {['name'] = 'poor_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pronghorn_01
    ['perfect_pronghorn_pelt']   = {['name'] = 'perfect_pronghorn_pelt',   ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pronghorn_pelt']      = {['name'] = 'good_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pronghorn_pelt']      = {['name'] = 'poor_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bighornram_01
    ['perfect_bighornram_pelt']  = {['name'] = 'perfect_bighornram_pelt',  ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bighornram_pelt']     = {['name'] = 'good_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bighornram_pelt']     = {['name'] = 'poor_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_sheep_01
    ['perfect_sheep_pelt']       = {['name'] = 'perfect_sheep_pelt',       ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_sheep_pelt']          = {['name'] = 'good_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_sheep_pelt']          = {['name'] = 'poor_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_wolf
    ['perfect_wolf_pelt']        = {['name'] = 'perfect_wolf_pelt',        ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_wolf_pelt']           = {['name'] = 'good_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_wolf_pelt']           = {['name'] = 'poor_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_alligator_03
    ['perfect_alligator_pelt']   = {['name'] = 'perfect_alligator_pelt',   ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_alligator_pelt']      = {['name'] = 'good_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_alligator_pelt']      = {['name'] = 'poor_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- mp_a_c_alligator_01
    ['legendary_alligator_pelt'] = {['name'] = 'legendary_alligator_pelt', ['label'] = 'Leg Alligator Pelt', ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_beaver_01
    ['legendary_beaver_pelt']    = {['name'] = 'legendary_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_boar_01
    ['legendary_boar_pelt']      = {['name'] = 'legendary_boar_pelt',      ['label'] = 'Leg Boar Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_cougar_01
    ['legendary_cougar_pelt']    = {['name'] = 'legendary_cougar_pelt',    ['label'] = 'Leg Cougar Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_coyote_01
    ['legendary_coyote_pelt']    = {['name'] = 'legendary_coyote_pelt',    ['label'] = 'Leg Coyote Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_panther_01
    ['legendary_panther_pelt']   = {['name'] = 'legendary_panther_pelt',   ['label'] = 'Leg Panther Pelt',   ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_wolf_01
    ['legendary_wolf_pelt']      = {['name'] = 'legendary_wolf_pelt',      ['label'] = 'Leg Wolf Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- a_c_raccoon_01
    ['perfect_raccoon_pelt']   = {['name'] = 'perfect_raccoon_pelt',   ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_perfect.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_raccoon_pelt']      = {['name'] = 'good_raccoon_pelt',      ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_good.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_raccoon_pelt']      = {['name'] = 'poor_raccoon_pelt',      ['label'] = 'Raccoon Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_poor.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
