---------------
Insert the items into qr-core/shared/items.lua (edit any of the descriptions to fit your needs)
---------------
	
	-- fish
	['a_c_fishbluegil_01_ms']				= {['name'] = 'a_c_fishbluegil_01_ms',			['label'] = 'Blue Gil (M)',				['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_bluegill.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishbluegil_01_sm']				= {['name'] = 'a_c_fishbluegil_01_sm',			['label'] = 'Blue Gil (S)',				['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_bluegill.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishbullheadcat_01_ms']			= {['name'] = 'a_c_fishbullheadcat_01_ms',		['label'] = 'Bullhead Cat (M)',			['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_bullhead_catfish.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishbullheadcat_01_sm']			= {['name'] = 'a_c_fishbullheadcat_01_sm',		['label'] = 'Bullhead Cat (S)',			['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_bullhead_catfish.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishchainpickerel_01_ms']			= {['name'] = 'a_c_fishchainpickerel_01_ms',	['label'] = 'Chain Pickerel (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_chain_pickerel.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishchainpickerel_01_sm']			= {['name'] = 'a_c_fishchainpickerel_01_sm',	['label'] = 'Chain Pickerel (S)',		['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_chain_pickerel.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishchannelcatfish_01_lg']		= {['name'] = 'a_c_fishchannelcatfish_01_lg',	['label'] = 'Channel Catfish (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_channel_catfish.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishchannelcatfish_01_xl']		= {['name'] = 'a_c_fishchannelcatfish_01_xl',	['label'] = 'Channel Catfish (EL)',		['weight'] = 1000,	['type'] = 'item',	['image'] = 'provision_fish_channel_catfish.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishlakesturgeon_01_lg']			= {['name'] = 'a_c_fishlakesturgeon_01_lg',		['label'] = 'Lake Sturgeon (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_lake_sturgeon.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishlargemouthbass_01_lg']		= {['name'] = 'a_c_fishlargemouthbass_01_lg',	['label'] = 'Large Mouth Bass (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_largemouth_bass.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishlargemouthbass_01_ms']		= {['name'] = 'a_c_fishlargemouthbass_01_ms',	['label'] = 'Large Mouth Bass (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_largemouth_bass.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishlongnosegar_01_lg']			= {['name'] = 'a_c_fishlongnosegar_01_lg',		['label'] = 'Long Nose Gar (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_longnose_gar.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishmuskie_01_lg']				= {['name'] = 'a_c_fishmuskie_01_lg',			['label'] = 'Muskie (L)',				['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_muskie.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishnorthernpike_01_lg']			= {['name'] = 'a_c_fishnorthernpike_01_lg',		['label'] = 'Northern Pike (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_northern_pike.png',			['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishperch_01_ms']					= {['name'] = 'a_c_fishperch_01_ms',			['label'] = 'Perch (M)',				['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_perch.png',					['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishperch_01_sm']					= {['name'] = 'a_c_fishperch_01_sm',			['label'] = 'Perch (S)',				['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_perch.png',					['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishrainbowtrout_01_lg']			= {['name'] = 'a_c_fishrainbowtrout_01_lg',		['label'] = 'Rainbow Trout (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_speckled_trout.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishrainbowtrout_01_ms']			= {['name'] = 'a_c_fishrainbowtrout_01_ms',		['label'] = 'Rainbow Trout (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_speckled_trout.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishredfinpickerel_01_ms']		= {['name'] = 'a_c_fishredfinpickerel_01_ms',	['label'] = 'Red Fin Pickerel (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_redfin_pickerel.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishredfinpickerel_01_sm']		= {['name'] = 'a_c_fishredfinpickerel_01_sm',	['label'] = 'Red Fin Pickerel (S)',		['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_redfin_pickerel.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishrockbass_01_ms']				= {['name'] = 'a_c_fishrockbass_01_ms',			['label'] = 'Rock Bass (M)',			['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_rock_bass.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishrockbass_01_sm']				= {['name'] = 'a_c_fishrockbass_01_sm',			['label'] = 'Rock Bass (S)',			['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_fish_rock_bass.png',				['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishsalmonsockeye_01_lg']			= {['name'] = 'a_c_fishsalmonsockeye_01_lg',	['label'] = 'Salmon Sockeye (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_sockeye_salmon.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishsalmonsockeye_01_ml']			= {['name'] = 'a_c_fishsalmonsockeye_01_ml',	['label'] = 'Salmon Sockeye (ML)',		['weight'] = 800,	['type'] = 'item',	['image'] = 'provision_fish_sockeye_salmon.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishsalmonsockeye_01_ms']			= {['name'] = 'a_c_fishsalmonsockeye_01_ms',	['label'] = 'Salmon Sockeye (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_sockeye_salmon.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishsmallmouthbass_01_lg']		= {['name'] = 'a_c_fishsmallmouthbass_01_lg',	['label'] = 'Small Mouth Bass (L)',		['weight'] = 900,	['type'] = 'item',	['image'] = 'provision_fish_smallmouth_bass.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['a_c_fishsmallmouthbass_01_ms']		= {['name'] = 'a_c_fishsmallmouthbass_01_ms',	['label'] = 'Small Mouth Bass (M)',		['weight'] = 600,	['type'] = 'item',	['image'] = 'provision_fish_smallmouth_bass.png',		['unique'] = true,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},

	-- fishing bait
	['p_baitbread01x']						= {['name'] = 'p_baitbread01x',					['label'] = 'Bread Bait',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_bread.png',				['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_baitcorn01x']						= {['name'] = 'p_baitcorn01x',					['label'] = 'Corn Bait',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_corn.png',				['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_baitcheese01x']						= {['name'] = 'p_baitcheese01x',				['label'] = 'Cheese Bait',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_cheese.png',				['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_baitworm01x']						= {['name'] = 'p_baitworm01x',					['label'] = 'Worm Bait',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_worm.png',				['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_baitcricket01x']					= {['name'] = 'p_baitcricket01x',				['label'] = 'Cricket Bait',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_cricket.png',				['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_crawdad01x']						= {['name'] = 'p_crawdad01x',					['label'] = 'Crawfish Bait',			['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_crayfish.png',			['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	-- fishing lures
	['p_finishedragonfly01x']				= {['name'] = 'p_finishedragonfly01x',			['label'] = 'Dragonfly Lure',			['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_leg_lure_river.png',		['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_finisdfishlure01x']					= {['name'] = 'p_finisdfishlure01x',			['label'] = 'Fish Lure',				['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',		['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_finishdcrawd01x']					= {['name'] = 'p_finishdcrawd01x',				['label'] = 'Crawfish Lure',			['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_leg_lure_swamp.png',		['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_finishedragonflylegendary01x']		= {['name'] = 'p_finishedragonflylegendary01x',	['label'] = 'Legendary Dragonfly Lure',	['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_lure_lake.png',			['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_finisdfishlurelegendary01x']		= {['name'] = 'p_finisdfishlurelegendary01x',	['label'] = 'Legendary Fish Lure',		['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_lure_lake.png',			['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_finishdcrawdlegendary01x']			= {['name'] = 'p_finishdcrawdlegendary01x',		['label'] = 'Legendary Crawfish Lure',	['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_lure_lake.png',			['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_lgoc_spinner_v4']					= {['name'] = 'p_lgoc_spinner_v4',				['label'] = 'Spinner',					['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',		['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['p_lgoc_spinner_v6']					= {['name'] = 'p_lgoc_spinner_v6',				['label'] = 'Improved Spinner',			['weight'] = 10,	['type'] = 'item',	['image'] = 'upgrade_fsh_bait_leg_lure_lake.png',		['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},

	-- add to your weapon items
	['weapon_fishingrod']	= {['name'] = 'weapon_fishingrod',	['attachPoint'] = 13,	['label'] = 'Fishingrod',	['weight'] = 500,	['type'] = 'weapon',	['ammotype'] = nil,	['image'] = 'weapon_fishingrod.png',	['unique'] = true,	['useable'] = true,	['level'] = 0,	['description'] = 'Fishingrod'},

---------------